language: node_js
node_js:
  - '>=8'
before_install:
  - yarn global add greenkeeper-lockfile@1 sequelize-cli
before_script:
  - greenkeeper-lockfile-update
  - yarn
  - yarn migrate:test
after_script:
  - greenkeeper-lockfile-upload
  - yarn migrate:test:undo
cache:
  yarn: true
  directories:
    - 'node_modules'
